### ISSUE TITLE
Make a simple website

### ISSUE THREAD

**Issue by coderdiaz** [coderdiaz/vue-transformicons#1]
Please fork the repository and make:
1. `yarn install`.
2. `yarn serve`.
3. Go to `http://localhost:4000`.

This is a example for website:
https://coderdiaz.me/vue-tiny-pagination/

**Comment by danomah** [comment]
I can help with this if you'd like? What are you looking for?

**Comment by coderdiaz** [comment]
Hi @danomah, you can see the `example` dir. Please fork the repository and make:
1. `yarn install`.
2. `yarn serve`.
3. Go to `http://localhost:4000`.

This is a example for website:
https://coderdiaz.me/vue-tiny-pagination/
